name: Code Linter

on:
  push:
  pull_request:

jobs:
  code_linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pull Docker image
      run: docker pull "docker.pkg.github.com/michaelbrockus/ubuntu-ci-sys:latest"

    - name: Run image
      run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/workspace -w /workspace docker.pkg.github.com/michaelbrockus/ubuntu-ci-sys:latest

    - name: Setup, Test and Linter
      run: docker exec builder bash -c 'meson setup build && meson compile -C build && cppcheck --project=build/compile_commands.json'
